/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JPanel;

/**
 * @author KIM
 * @author MOLI
 * @author GEM
 * @author CHERRY
 */

public class HealsUI extends javax.swing.JFrame {

Connection con = null;
PreparedStatement ps =null;
ResultSet rs = null;
    

    /**
     * Creates new form HealsUI
     * 
     * DATABASE NAME = db_heals
     * 
     */
    
    
    public HealsUI() {
        initComponents();
        this.setLocationRelativeTo(null);       //start at center of screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pHolder = new javax.swing.JPanel();
        pHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        b_adminUI = new javax.swing.JButton();
        b_receptionistUI = new javax.swing.JButton();
        b_doctorUI = new javax.swing.JButton();
        bg_Home = new javax.swing.JLabel();
        pDoctor = new javax.swing.JPanel();
        pAdmin = new javax.swing.JPanel();
        pRecep = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_stfUserLog = new javax.swing.JTextField();
        pf_stfPassLog = new javax.swing.JPasswordField();
        l_user = new javax.swing.JLabel();
        l_pass = new javax.swing.JLabel();
        b_stfLogin = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setEnabled(false);

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("About");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 204, 0), null));
        jButton1.setContentAreaFilled(false);

        jButton2.setBackground(new java.awt.Color(0, 51, 102));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Logout");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 204, 0), null));
        jButton2.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(528, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pHolder.setLayout(new java.awt.CardLayout());

        pHome.setBackground(new java.awt.Color(255, 255, 255));
        pHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 128, 255));
        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 42)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("    HEALS");
        jLabel1.setOpaque(true);
        pHome.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1200, 80));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 128, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" ADMIN");
        pHome.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 180, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 128, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(" DOCTOR");
        pHome.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 180, 40));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 128, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("  RECEPTIONIST");
        pHome.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 500, 180, 40));

        b_adminUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Businessman_100px.png"))); // NOI18N
        b_adminUI.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(0, 102, 153), new java.awt.Color(0, 51, 51)));
        pHome.add(b_adminUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 180, 180));

        b_receptionistUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Front Desk_100px.png"))); // NOI18N
        b_receptionistUI.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(0, 102, 153), new java.awt.Color(0, 51, 51)));
        b_receptionistUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_receptionistUIActionPerformed(evt);
            }
        });
        pHome.add(b_receptionistUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, 180, 180));

        b_doctorUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/Stethoscope_100px.png"))); // NOI18N
        b_doctorUI.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(0, 102, 153), new java.awt.Color(0, 51, 51)));
        pHome.add(b_doctorUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 180, 180));

        bg_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/soft-white-backgrounds-wallpapers.jpg"))); // NOI18N
        bg_Home.setText("jLabel2");
        pHome.add(bg_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, -60, -1, -1));

        pHolder.add(pHome, "card2");

        javax.swing.GroupLayout pDoctorLayout = new javax.swing.GroupLayout(pDoctor);
        pDoctor.setLayout(pDoctorLayout);
        pDoctorLayout.setHorizontalGroup(
            pDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        pDoctorLayout.setVerticalGroup(
            pDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        pHolder.add(pDoctor, "card3");

        javax.swing.GroupLayout pAdminLayout = new javax.swing.GroupLayout(pAdmin);
        pAdmin.setLayout(pAdminLayout);
        pAdminLayout.setHorizontalGroup(
            pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        pAdminLayout.setVerticalGroup(
            pAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        pHolder.add(pAdmin, "card4");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 128, 255));
        jLabel2.setFont(new java.awt.Font("Felix Titling", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("   Front desk");
        jLabel2.setOpaque(true);

        tf_stfUserLog.setFont(new java.awt.Font("HelvLight", 0, 14)); // NOI18N
        tf_stfUserLog.setBorder(null);
        tf_stfUserLog.setOpaque(true);

        pf_stfPassLog.setFont(new java.awt.Font("HelvLight", 0, 14)); // NOI18N
        pf_stfPassLog.setBorder(null);
        pf_stfPassLog.setOpaque(true);
        pf_stfPassLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_stfPassLogActionPerformed(evt);
            }
        });

        l_user.setBackground(new java.awt.Color(255, 255, 255));
        l_user.setFont(new java.awt.Font("HelvLight", 0, 18)); // NOI18N
        l_user.setForeground(new java.awt.Color(0, 128, 255));
        l_user.setText("Username:");

        l_pass.setBackground(new java.awt.Color(255, 255, 255));
        l_pass.setFont(new java.awt.Font("HelvLight", 0, 18)); // NOI18N
        l_pass.setForeground(new java.awt.Color(0, 128, 255));
        l_pass.setText("Password:");

        b_stfLogin.setText("LOGIN");
        b_stfLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_stfLoginActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(204, 255, 255));
        jSeparator1.setOpaque(true);

        jSeparator3.setBackground(new java.awt.Color(204, 255, 255));
        jSeparator3.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_pass)
                    .addComponent(l_user)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pf_stfPassLog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_stfUserLog, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(430, 430, 430))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(587, 587, 587)
                    .addComponent(b_stfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(547, 547, 547)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(l_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_stfUserLog, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(l_pass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_stfPassLog, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(432, 432, 432)
                    .addComponent(b_stfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(210, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pRecepLayout = new javax.swing.GroupLayout(pRecep);
        pRecep.setLayout(pRecepLayout);
        pRecepLayout.setHorizontalGroup(
            pRecepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRecepLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pRecepLayout.setVerticalGroup(
            pRecepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pHolder.add(pRecep, "card5");

        getContentPane().add(pHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
  
    
    //method to connect to database
    void connectToDB(){                                   
        try {
            String host = "jdbc:mysql://localhost:3306/db_heals";
            con = DriverManager.getConnection(host, "root", "");
            }
        catch ( SQLException err ) {
            javax.swing.JOptionPane.showMessageDialog(this,"Error connecting to database:\n"+ err);
            }
    }
    
    
    //method to switch pages
    void SwitchPage(JPanel source, JPanel destination){
    source.removeAll();
    source.repaint();
    source.revalidate();
    source.add(destination);
    source.repaint();
    source.revalidate();
    }
    
    
    
    private void b_receptionistUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_receptionistUIActionPerformed
        // TODO add your handling code here:
        SwitchPage(pHolder, pRecep);
    }//GEN-LAST:event_b_receptionistUIActionPerformed

    private void pf_stfPassLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_stfPassLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_stfPassLogActionPerformed

    private void b_stfLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_stfLoginActionPerformed
        if (sampleUser.equals(tf_stfUserLog.getText()) && samplePass.equals(pf_stfPassLog.getText())) {
            SwitchPage(StaffUI, Staff_MAIN);
        }
    }//GEN-LAST:event_b_stfLoginActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HealsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HealsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HealsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HealsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HealsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_adminUI;
    private javax.swing.JButton b_doctorUI;
    private javax.swing.JButton b_receptionistUI;
    private javax.swing.JButton b_stfLogin;
    private javax.swing.JLabel bg_Home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel l_pass;
    private javax.swing.JLabel l_user;
    private javax.swing.JPanel pAdmin;
    private javax.swing.JPanel pDoctor;
    private javax.swing.JPanel pHolder;
    private javax.swing.JPanel pHome;
    private javax.swing.JPanel pRecep;
    private javax.swing.JPasswordField pf_stfPassLog;
    private javax.swing.JTextField tf_stfUserLog;
    // End of variables declaration//GEN-END:variables
}
